### ISSUE TITLE
Project ID

### ISSUE THREAD

**Issue by shaveosphere** [cbrooker/MMM-Todoist#1]
great app - but How is it possible to find the Project ID number to display the list you want?

**Comment by cbrooker** [comment]
That's a good questions, I forgot to put that in the documentation. I did it by looking at the JSON returned from the Sync API. But the easier way is to get it from the Todoist URL:

1) Go to Todoist (Log in if you aren't)
2) Click on a Project in the left menu
3) Your browser URL will change to something like "https://todoist.com/app?lang=en&v=818#project%2F166564897"

Everything after %2F is the Project ID. In this case "166564897"

Hope that helps.
