### ISSUE TITLE
Labels not displaying results

### ISSUE THREAD

**Issue by danhuss** [cbrooker/MMM-Todoist#111]
I probably just need some help troubleshooting this, but I'm not able to get any tasks to display when using just the "labels" configuration option. I know I have tasks with the label I'm trying to display, and it's showing tasks when I use the project option. So far I've tried single and double quotes around the label name, using the label number instead of the string name, and various casing options. The only other one I've found similar to this is #68 but that sounds like it ended up being a configuration error, which shouldn't be the case if I can get data with other options, right? Is there some log I could look at to see what exactly is going on with the module?

Thanks,
Daniel

**Comment by lenikey** [comment]
+1 
Can't get the probably easiest case to get going: using one single list in todoist in which I have one single label. I only want to display the tasks with that label, however it's not showing on my MM.

**Comment by FutureYamask** [comment]
I created a pull request that fixes this problem: https://github.com/cbrooker/MMM-Todoist/pull/112

**Comment by danhuss** [comment]
That PR appears to have fixed it for me as well.
