### ISSUE TITLE
Order by date, priority

### ISSUE THREAD

**Issue by k01dun** [cbrooker/MMM-Todoist#20]
Hello,
 
Is there an option which would allow to order records by date, priority? Overdue first, then all records for Today, and so on, records with higher priority on the top.
![img_20180128_203501678](https://user-images.githubusercontent.com/20618052/35661453-20e374a2-06c7-11e8-8647-a9ad95be65ca.jpg)

**Comment by djsunrise19** [comment]
same question here!

**Comment by cbrooker** [comment]
Hey guys,

Sorry for the delay. I've added the ability to sort differently in different ways. Try out the different sort types and let me know if that's the behavior you're looking for. If not, can you give me an example of how you want it sorted and I'll add the option.

Chris

Get the latest code and add this to your config.

**sortType** 
This will determine the sorting method used when displaying your Todos.

Possible values: 
"todoist" - Sort based on the order in Todoist. 
"dueDateAsc" - Sort based on the Due Date of the Todo Ascending. (Oldest date first) 
"dueDateDesc" - Sort based on the Due Date of the Todo Descending. (Newest date first)

Default value: "todoist"

**Comment by djsunrise19** [comment]
That's it, thank you!

**Comment by k01dun** [comment]
Awesome! Thanks!
