### ISSUE TITLE
ToDos without any date / time

### ISSUE THREAD

**Issue by djsunrise19** [cbrooker/MMM-Todoist#23]
Hi,

since the last update, todos without a date or time specification gets a "12:59 AM". Beside I have the 24h metric, that doesn't seem to be correct, doesn't it?! The cell should be empty.

![image](https://user-images.githubusercontent.com/14234570/37710540-3d9eda10-2d0e-11e8-8405-bfe430600a76.png)

Best regards
Maurice

**Comment by cbrooker** [comment]
Hi Maurice,

My apologies, I didn't thoroughly test the last Pull request. I'll look into this today.

Thanks

**Comment by djsunrise19** [comment]
The 12/24h problem wasn't fixed:

![image](https://user-images.githubusercontent.com/14234570/37862552-fd4040d8-2f4e-11e8-99d0-94d03bff2e09.png)

**Comment by cbrooker** [comment]
Fixed
