### ISSUE TITLE
Could you please...

### ISSUE THREAD

**Issue by Sizer009** [cbrooker/MMM-Todoist#27]
Let me know how to alter the width as I have this in the center and need it wider, also how to remove the project name, I dont mind the dots but dont need to see the project name for every item on my shopping list. (also "Inbox" for the todo list) Many thanks for a great module.

**Comment by cbrooker** [comment]
Hi,

1) The width of the widget is dictated by the grid that MagicMirror is build upon. The widget will stretch to fit the width of the position in which it is placed. You can specify any of these positions (top_ bar, top_left, top_center, top_right, upper_third, middle_center, lower_third, bottom_left, bottom_center, bottom_right, bottom_bar, fullscreen_above, fullscreen_below.) Which you probably know.

If you need something a bit more custom you will probably have to modify MagicMirror's stylesheet to make it look exactly how you want. Could you send me a screenshot?

2) To remove the project name add this to your MM config for the MMM-Todoist module:
     `showProject: false`
