### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by dinkybluebug** [cbrooker/MMM-Todoist#3]
Hi - 

My todoist module isnt updating -  no error messages either in the console.  Items dont come off the todo list.

Looking at the readme file - is the update interval in seconds or minutes?  I noticed that in the readme file MaximumEntries  and Interval both refers how often it updates:

**maximumEntries**
Possible values: time in min 
Default value: 60

**interval**	
How often the module should load new todos.
Possible values: int in seconds 
Default value: 60

can you clarify?  Is the interval in seconds or mins?

Thanks

**Comment by dinkybluebug** [comment]
Right Ive worked out the issue - when I had items to my todo list - it appears in the module. But when the items are completed / or deleted - they don't come off. Any ideas why?

**Comment by kasperb2** [comment]
I've been having a similar issue recently. The odd thing is, it was working fine previously. Have you been able to resolve this issue yet? What troubleshooting steps have you taken so far?

**Comment by dinkybluebug** [comment]
I haven't really. As in I don't know what it could be. It still doesn't work. Things go on but they don't come off (until something else goes on)

**Comment by joela85** [comment]
I have the same problem, haven't worked out a way around this yet? Has anyone else?

**Comment by kasperb2** [comment]
After generating a new Todoist token, the issue was resolved on my end. I've also re-installed my MM, so that might have contributed to the resolution as well :-)

**Comment by joela85** [comment]
Tried a new token, it loaded up what I had in my list, but when adding new items, they never got added to the mirror. Can't see how the code is updating the list.
