### ISSUE TITLE
Is there a way to cap width of widget?

### ISSUE THREAD

**Issue by kquinsland** [cbrooker/MMM-Todoist#30]
It looks like a similar ask was raised in https://github.com/cbrooker/MMM-Todoist/issues/27, so close this if it's the same answer.

Is there a max width I can apply?  I'm not super familiar w/ how MMirror does all it's layouts and width calculations for the grid, but it looks like the do not put a hard limit on width?

I have _one_ *really* long task in Todoist/Inbox.  It's not a common thing, just a kinda occasional edge-case.  This really long task is stretching out the widget so it's clobbering others.  I'll get this task cleaned up / organized soon, so it'll stop being an issue soon... I just wanted to ask while i still noticed / could take a screenshot. 

![magicmirror](https://user-images.githubusercontent.com/1808375/42139991-f5e88146-7d4c-11e8-91b0-336ab831e63a.jpg)

Is there something that i can do w/ the API to limit this or should i get a quick PR in?

JS is ... not a core strength of mine, so it'd be dirty / look something like:

`item.length >= 60 ? item.substring(0,60) : item` 

(where 60 should probably be something users can override...)

somewhere around here:
https://github.com/cbrooker/MMM-Todoist/blob/master/MMM-Todoist.js#L95

-K

**Comment by AgP42** [comment]
Hello, 

I just propose a pull request to allow to display tasks on several lines (as the official module "calendar"). 
You can check it on the "Pull request" tab or [here ](https://github.com/AgP42/MMM-Todoist)
