### ISSUE TITLE
ToDo's without a date have: Jan 01 2101

### ISSUE THREAD

**Issue by djsunrise19** [cbrooker/MMM-Todoist#32]
Hi,

as you can see in the screenshot, todos without a date have default: Jan 01 2101

<img width="259" alt="image" src="https://user-images.githubusercontent.com/14234570/43100067-744c37f2-8ec4-11e8-8459-45a3c3d164b2.png">

Regards
Maurice

**Comment by AgP42** [comment]
I have 2 MagicMirror, for ToDoIst module I use the same config file for both Mirror. On one (RPI2) I don't have the same issue, the task is displayed without any "dueDate", and on the other one (RPI3) I got like Maurice the display "Jan 1 2101" for tasks without dueDate. 
Very strange...
Both my MM are in version 2.4.1 and the dev console told me they are both running Chrome 61.

**Comment by AgP42** [comment]
I find the origine of the issue. 
In fact my 2 Mirror was on the same config but not on the same Module version, on one I merged to the new master and not the other, and this behaviour has been introduced by the last [commit #28 ](https://github.com/cbrooker/MMM-Todoist/pull/28)
So this is a regression. 

I just proposed a correction on my pull request already open, see here : [https://github.com/cbrooker/MMM-Todoist/pull/31/commits/3a2d0f0516289cf37db65728bd4f8874d7f2880e](https://github.com/cbrooker/MMM-Todoist/pull/31/commits/3a2d0f0516289cf37db65728bd4f8874d7f2880e)

**Comment by djsunrise19** [comment]
It works for me now!
