### ISSUE TITLE
Project Alignment

### ISSUE THREAD

**Issue by nctyb09** [cbrooker/MMM-Todoist#34]
When arraying multiple projects to a single module and displaying the name in the module, my project names do not alight right as the due date does. Is there a parameter that can adjust this?

Thanks!
Nick

**Comment by rickycantrell** [comment]
Hey Nick any chance you ever solved this one?

**Comment by cbrooker** [comment]
I know this is an old post. Are you still having this problem? If so, could you create a new issue and post a screen shot?
