### ISSUE TITLE
Done tasks still appearing and different views

### ISSUE THREAD

**Issue by funker** [cbrooker/MMM-Todoist#35]
Hey there,

just got into the MagicMirror thing and I love it. Your Todoist module was the first I installed and instantly got it to work.
Now there is one issue and one request:
### 1. The issue
I have several tasks already marked as done, but they still appear on the smart mirror as if they were new. Is there a fix for this?

### 2. The request
I have a large amount of projects in Todoist but I don't really care for them. I normally use the "today" and the "next 7 days" views.
Is it somehow possible to get the module show these views instead of just projects, that I manually need to add to the config?

Would be great hearing from you.
Have a nice day.
Jan

**Comment by cbrooker** [comment]
Hi Jan,

I'm happy to hear you're enjoying your MM. It's a great platform.

I'll try to help you with your issues.

Issues 1.
The module only pulls updates from Todoist every 5 mins iirc. So you won't see the status change immediately. Are you seeing really old completed items?

2)
You can currently only show lists that have IDs associated to them. All projects have IDs and well as the Inbox. "Today" and "Next 7 days" are handled differently within Todoist and haven't yet been implemented in this Module. It's on the road map to add in the future but I have had very little free time to add it. Perhaps someone in the community can add this feature.

**Comment by funker** [comment]
Thanks for your quick response. The today view would be a great addition, because I want to put the SmartMirror right next to my door. I also track which trash can I need to get out which day and other organizational stuff with Todoist. I hope someone could implement this. 
The completed tasks are pretty old. Way older than five minutes. Maybe there is an issue with tasks and sub-tasks which I use pretty regularly?
