### ISSUE TITLE
A way to add another Todoist account (multiple users)

### ISSUE THREAD

**Issue by thebmfinn** [cbrooker/MMM-Todoist#40]
Is there a way to add multiple Todoist accounts? E.g. add multiple access tokens, or add another ProjectID from someone else's account? I tried simply adding another project ID from a different account separated by a common and it did not seem to work, I assume each account needs its own unique access token

**Comment by cbrooker** [comment]
HI thebmfinn,

The easiest way to do that without major code changes is to add a second Widget to your mm config file with different settings.

In you mm config add a second MMM-Todoist module with the other settings.
```
{
		module: 'MMM-Todoist',
		position: 'top_right',	// This can be any of the regions. Best results in left or right regions.
		header: 'Todoist', // This is optional
		config: { // See 'Configuration options' for more information.
          	accessToken: 'accessToken from Todoist',
			maximumEntries: 60,
			updateInterval: 10*60*1000, // Update every 10 minutes
			projects: [ 166564794 ], //this entry is mandatory
			fade: false
      },
    {
		module: 'MMM-Todoist',
		position: 'top_right',	// This can be any of the regions. Best results in left or right regions.
		header: 'Todoist', // This is optional
		config: { // See 'Configuration options' for more information.
          	accessToken: 'accessToken from Todoist for the other account',
			maximumEntries: 60,
			updateInterval: 10*60*1000, // Update every 10 minutes
			projects: [ 166564794 ], //this entry is mandatory
			fade: false
      }
```

**Comment by thebmfinn** [comment]
That is a simple and effective suggestion. thanks! I added it just now (a second module with its own access token and project ID in the same region) and it seems to be only showing one list at a time. It refreshes and switches which account it shows (not showing both at the same time)

**Comment by cbrooker** [comment]
Interesting.. Let me do some testing tomorrow and I'll see if I can find a solution.

**Comment by cbrooker** [comment]
Hey,

I investigated further and had to make a few code changes. Try again with 2 MMM-Todoist widgets each configured to a different account. I should now work. Let me know how it works when you get a chance to test.

Thanks for bringing this problem up.

**Comment by thebmfinn** [comment]
I did a ` git pull` in to update the module and it worked perfectly! I have both To do list accounts up and running

**Comment by cbrooker** [comment]
Awesome, thanks for validating that everything is working.
