### ISSUE TITLE
Only Showing One Project

### ISSUE THREAD

**Issue by brandongomez** [cbrooker/MMM-Todoist#46]
Hi there. Great module! Love it! Only issue I'm having right now is that it is only displaying one project. I have copied over the project ID's (3 of 'em) but it will only show one. If I try each one individually, only one is displaying which is really weird. I know I'm copying the right project number: https://todoist.com/app#project%2F<this_number>%2Ffull

Any ideas on what could be wrong here? Thanks!

**Comment by cbrooker** [comment]
Hey,
I know this is a very old issue. Are you still having any problems?

**Comment by brandongomez** [comment]
All good now, thanks!
