### ISSUE TITLE
Give the options to show all projects of a user

### ISSUE THREAD

**Issue by samusaran** [cbrooker/MMM-Todoist#47]
It would be nice to not enforce the project Id inside the configuration, since a user may have short-lived projects and does not want to update the configuration every time.

**Comment by samusaran** [comment]
The referenced commit seems to work just fine. Let me know if that's enough, so I can create a PR.

**Comment by tintinmaster** [comment]
For me this works fine and it is far more enjoyable.
Would be nice if you could make a blacklist, so you choose which projects  **not** to display
