### ISSUE TITLE
Error log:  Invalid date

### ISSUE THREAD

**Issue by xuepgao** [cbrooker/MMM-Todoist#48]
@cbrooker 

Thank you for providing us this fantastic module!

My MMM-Todoist works fine. But I found a error log in console:
`[12208:0523/220203.528255:INFO:CONSOLE(201)] "ToDoIst update OK, project : 22107111111 at : Invalid date", source: http://0.0.0.0:8080/modules/MMM-Todoist//MMM-Todoist.js (201)`

I'd like to know what it mean.  How can I make it disappear? Could you give me some suggestions? Thanks.

**Comment by cbrooker** [comment]
It's been fixed. Please do a 'git pull' in the modules/MMM-Todoist folder
