### ISSUE TITLE
ProjectID's don't match ?

### ISSUE THREAD

**Issue by macoopma** [cbrooker/MMM-Todoist#49]
When looking for the projectID using the method described (from the URL taking the %2F out) doesn't seem to work ? 
I found the correct ones using an sample from the toDoist API documentation : 
https://todoist.com/api/v7/sync?token=_INSERT_YOUR_TOKEN_HERE_&sync_token=*&resource_types=["projects"]

this way I got totally different projectID's , and those work just fine !

**Comment by Aikagi000** [comment]
tried the way of the module instructions AND the way posted by OP. Both ways gave me the same project ID but it still doesn't work. All it says is "loading"

**Comment by cbrooker** [comment]
If you grab the latest code ("git pull" in the MMM-Todoist folder) and add "debug=true" in the Todoist section of your config.js, when you load the page it will dump all the Projects and Project IDs to your screen. You can double check them there.
