### ISSUE TITLE
TypeError and request error in latest version

### ISSUE THREAD

**Issue by jefftriplett** [cbrooker/MMM-Todoist#5]
Since this past update, I have been seeing several error like:

```
0|mm       | Whoops! There was an uncaught exception...
0|mm       | TypeError: Cannot read property 'substring' of null
0|mm       |     at Request._callback (/home/pi/MagicMirror/modules/MMM-Todoist/fetcher.js:69:35)
0|mm       |     at Request.self.callback (/home/pi/MagicMirror/modules/MMM-Todoist/node_modules/request/request.js:187:22)
0|mm       |     at emitTwo (events.js:106:13)
0|mm       |     at Request.emit (events.js:191:7)
0|mm       |     at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-Todoist/node_modules/request/request.js:1126:10)
0|mm       |     at emitOne (events.js:96:13)
0|mm       |     at Request.emit (events.js:188:7)
0|mm       |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Todoist/node_modules/request/request.js:1046:12)
0|mm       |     at IncomingMessage.g (events.js:286:16)
0|mm       |     at emitNone (events.js:91:20)
0|mm       | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```

I don't know much about node but it appears it's not happy with request. All of my other plugins work so I don't think it's related to he latest MM update but I'm feeling around in the dark here. 

My configs look like: 

```json
{
    module: 'MMM-Todoist',
    position: 'bottom_left',
    header: 'Personal Goals',
    config: {
        accessToken: 'removed-but-verified',
        maximumEntries: 10,
        interval: 60,
        lists: [ removed-but-verified ],
        fade: false
    }

```

I'm happy to help troubleshoot.

**Comment by tkotz8105** [comment]
Hi Jeff... 
Based on the stack error  message:  TypeError: Cannot read property 'substring' of null
                             at Request._callback (/home/pi/MagicMirror/modules/MMM-Todoist/fetcher.js:69:35)... it might be something with one of your Todoist entries.  I've just started using Todoist a few months back and added the code to MMM-Todoist to sort by due date.  Is it possible that one of your Todoist entries may be corrupted or not have a due date?
Tom

**Comment by jefftriplett** [comment]
Thank you for the tips. I'll double check from my office tomorrow. I actually don't have due dates on anything and have used this for a few months. So maybe that's it. I'll try a little harder to debug and confirm. I did check for any blank entries in todoist, but I'm not seeing anything.

**Comment by MrJuless** [comment]
I've got exactly the same problem. It worked fine for month and now i got this issue.
If anybody has an idea please help. I reinstalled the module but the issue occurs again.

best,
jules

**Comment by MrJuless** [comment]
Hi all,
i found out that the error only occurs if you have a task without a due date.
Now my problem is that i build tasks with alexa, alexa puts no due date on the tasks. ist there away to automaticly attach a due date to all tasks?

best,
Jules

**Comment by tkotz8105** [comment]
Hi Jules...
Thanks for helping to determine the problem.  I know the Android Todoist app defaults to today for due date but I don't think that is what you would want.  I found out the web-based Todoist  does allow for no due date... so I'm going to look at my code and see if I can put an exception code for the sorting when there is no due date.  I'm also going to check to make sure setting a time on the due date gets sorted properly.
Regards,
Tom

**Comment by tkotz8105** [comment]
OK... I did a quick test and workaround for a null or empty due date.  My workaround is to internally set a null due date to Friday, 31 Dec 2100 at 23:59:59.  This does not modify someone's actual Todoist's list ... it is just for sorting purposes.  I also tested the sequencing based on time and it works.  Can anyone else think of any other due date tests that I can try before I ask Chris Brooker to review and implement the fix?

**Comment by MrJuless** [comment]
Hi @tkotz8105 ,
many thanks for your fast response. That sounds great. I don't have an idea for other test. I think u set an exception that when due date is null 31 Dec 2100 is set right? That should solve the problem for AVS and all other services that don't set a due date.

many thanks, best,
jules

**Comment by jefftriplett** [comment]
Thanks for the updates! I appreciate you taking steps to find a fix. I use both the Todoist app for Mac and iOS which has no default date. I think having a really high date is a fine fix though. I would expect to see tasks with assigned dates with tasks without after. 

In case someone else has this problem, I rolled back to the commit before the date sorting change via `git checkout 155ffe4d49bd8af59ab8bb0736c3ad756c0515d6` as a workaround.
