### ISSUE TITLE
Floating Timezone: Today/Tomorrow incorrect

### ISSUE THREAD

**Issue by deyawper** [cbrooker/MMM-Todoist#54]
It appears that Todoist might have defaulted to a floating time zone. Which means that the Today/Tomorrow label changes according to GMT. So I (-8 GMT) keep having tomorrow's due dates, show as today. I'm able to work around by adding a time due (which adds a local timezone).

**Comment by theloniuser** [comment]
Yes. This is true. It does throw me off to see "Yesterday" displayed instead of "Today".

**Comment by KindledFlames** [comment]
I just installed the Todoist module today, so I'm not sure how useful this fix is, but I simply added 1 to var diffDays on line 441 in MMM-Todoist.js. I'll watch to find out how many hours mine is off by to see if I can figure out a permanent solution so everyone can have their correct timezone.
