### ISSUE TITLE
Changing Font on MMM-Todoist

### ISSUE THREAD

**Issue by roccodicarlo** [cbrooker/MMM-Todoist#57]
How can the fonts of the Project Title and/or the events be changed? Specifically I would like to change the size

**Comment by cbrooker** [comment]
Hey,

There is no configuration option for changing the fonts however, you can edit the MMM-Todoist.css file to change anything you want. 
The easiest way to adjust the title is to add this to your /modules/MMM-Todoist.css

> .MMM-Todoist .small {
>     font-size: 10px;
> }

default value is 20px.

This module is using the standard font sizes prescribed by MagicMirror.
