### ISSUE TITLE
img tag affect other modules

### ISSUE THREAD

**Issue by drdada** [cbrooker/MMM-Todoist#60]
Hello,
Since commit #58 (4a0af4b7619015f5d7fa3562e9d203efd0567a9a) todoist module is breaking images from other modules (e.g. MMM-Wallpaper or MMM-reddit).

I think it's because of the css file in the **.img** section, it affects ALL images.
I'm not very familiar with MM² or JS, so i'm not able to find a clean fix for it and do a PR. 
I have temporarily commented the img section in /MMM-Todoist.css

**Comment by cbrooker** [comment]
Thanks I'll take a look at it.

**Comment by cbrooker** [comment]
It's fixed. I should have more closely reviewed Pull requests.
