### ISSUE TITLE
Use Todoist "REST API" rather than "Sync API"

### ISSUE THREAD

**Issue by m-roberts** [cbrooker/MMM-Todoist#61]
This project is currently using the [Sync API](https://developer.todoist.com/sync/v8/) over the [REST API](https://developer.todoist.com/rest/v1/).

It strikes me that this is not the best approach - the purpose of this module is to display to-dos. Rather than pulling in all of the account data via a sync request and filtering it out, it seems like it would be better to use the REST API to query for the specific tasks to be shown.

This is beneficial for multiple reasons:
* More efficient network call; good for low bandwidth and large projects
* Allows for filtering by Todoist filters

Looking at the [REST API docs for getting active tasks](https://developer.todoist.com/rest/v1/#get-active-tasks), it seems pretty simple to retrieve tasks in this way.

It easily allows for filtering tasks by project ID and label for all (making this an easy under-the-hood swap-out for the current implementation, with no breaking changes to the config layout), and also allows for filtering by labels for Todoist Premium, which can be added to the config specification.

This *would* change behaviour in one way, though:
Currently, if both projects and labels are specified, then tasks from both will be shown. In this new implementation, then it would only show tasks that matched all filtering in the request (i.e. only tasks in the specified projects with specified labels and filters.

However, I feel that this is more appropriate. If this is important, then perhaps it can be added as a flag, which would choose which API to use, based on required functionality? I can imagine that someone on the free version of Todoist might want the existing functionality, but someone on Todoist Premium can get that level of control via a filter quite easily, and more precisely.

**Comment by cbrooker** [comment]
Hi,

You're absolutely correct. However, the todoist REST API didn't exist when this module was written. The Sync API was the only way to access todoist data.

I don't use this module anymore and have not been doing any real development on it in a while. If you want to fork it and do an overhaul, please do.

Thanks.
