### ISSUE TITLE
Help a Noob, module installed, read all issues... Cannot display lists other then inbox

### ISSUE THREAD

**Issue by Bernard-h** [cbrooker/MMM-Todoist#62]
I carefully read all treads and tried all possible solutions to get the module to work (Feb 2020)
My configs are all updated, the module runs, but it doesnt show any items. I have some images of the todisih developer hub, config.js and MMM-Todoist.js.

Im really stuck, can anyone have a look with me? Would be very much appreciated.

![Schermafbeelding 2020-02-06 om 00 19 21](https://user-images.githubusercontent.com/60395872/73892376-0d51e380-4877-11ea-89ed-626b01becb9e.png)
![Schermafbeelding 2020-02-06 om 00 18 04](https://user-images.githubusercontent.com/60395872/73892388-117e0100-4877-11ea-8907-fea3dc69d5b5.png)
![Schermafbeelding 2020-02-06 om 00 16 27](https://user-images.githubusercontent.com/60395872/73892391-1347c480-4877-11ea-857b-22c432f11dec.png)

**Comment by Bernard-h** [comment]
I can view the default inbox items when I add those project ids to the config.js and default MMM-todoist.js So thats a step forward. Good to know the access token works. 
Now ill be trying to figure out how to get those alexa generated to-do and shopping lists working... :(

**Comment by cbrooker** [comment]
Hey Bernard-h,

It sounds to me like the Project Ids you're putting in your config.js file are incorrect. I've added a little extra debugging help for you and anyone that might need it.

If you grab the latest code ("git pull" in the MMM-Todoist folder) and add "debug=true" in the Todoist section of your config.js, when you load the page it will dump all the Projects and Project IDs to your screen. You can double check them there.

I also recommend putting 'single quotes' around the ProjectIds in the config.js. From your screen shot it looks like they're missing.

If you're testing in a regular browser, also check the console and let me know if there are any errors.

Chris

**Comment by cbrooker** [comment]
Oh, also looking at your update interval. It's going to be hitting Todoist every second. You'll quickly hit your API call limit and Todoist will stop sending any data.

Try setting updateLimit to "60*1000". It will hit the API every minute.

updateLimit is in milliseconds.

**Comment by Bernard-h** [comment]
This issue has been resolved.
Thank you thank you
