### ISSUE TITLE
only show tasks in a certain time frame

### ISSUE THREAD

**Issue by Clubjack1** [cbrooker/MMM-Todoist#63]
Hey.

is it possible to add a function to change the  maximumNumberOfDays where shown the tasks?
(like in the calendar-module)

**Comment by cbrooker** [comment]
Hey,

Have you tried the "displayTasksWithinDays" config property?

If that doesn't do what you want could you provide more detail about the behavior you're looking for?

**Comment by Clubjack1** [comment]
Thank You.
I missunderstand the "displayTasksWithinDays" config.
Sorry. 
I think that will work
