### ISSUE TITLE
Show all Projects and blacklist ones you don't want

### ISSUE THREAD

**Issue by cbrooker** [cbrooker/MMM-Todoist#65]
For me this works fine and it is far more manageable.
Would be nice if you could make a blacklist, so you choose which projects  **not** to display

_Originally posted by @tintinmaster in https://github.com/cbrooker/MMM-Todoist/issues/47#issuecomment-490114154_

**Comment by nout-kleef** [comment]
Are you looking for help with this?
I'd like to give this a try.

**Comment by cbrooker** [comment]
Hi,

No I'm not currently looking at this. Please have a crack at it. :)
