### ISSUE TITLE
Module freezes when entries do not have a due date.

### ISSUE THREAD

**Issue by Chiumanfu** [cbrooker/MMM-Todoist#7]
If I add a to do list entry without a due date, the module does not load on startup and if it's already running, it stops updating. I've been able to reproduce this error consistently.

Here’s the log
Create new todo fetcher for list: 2153843199 - Interval: 60000
0|mm | Whoops! There was an uncaught exception…
0|mm | TypeError: Cannot read property ‘substring’ of null
0|mm | at Request._callback (/home/pi/MagicMirror/modules/MMM-Todoist/fetcher.js:69:35)
0|mm | at Request.self.callback (/home/pi/MagicMirror/modules/MMM-Todoist/node_modules/request/request.js:188:22)
0|mm | at emitTwo (events.js:106:13)
0|mm | at Request.emit (events.js:191:7)
0|mm | at Request. (/home/pi/MagicMirror/modules/MMM-Todoist/node_modules/request/request.js:1171:10)
0|mm | at emitOne (events.js:96:13)
0|mm | at Request.emit (events.js:188:7)
0|mm | at IncomingMessage. (/home/pi/MagicMirror/modules/MMM-Todoist/node_modules/request/request.js:1091:12)
0|mm | at Object.onceWrapper (events.js:290:19)
0|mm | at emitNone (events.js:91:20)
0|mm | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

**Comment by cbrooker** [comment]
This has been corrected. Thanks.
