### ISSUE TITLE
modify header

### ISSUE THREAD

**Issue by perlchamp** [cbrooker/MMM-Todoist#74]
hi,
is there a possibility to modify the header via css (or something else) ?
the font-size is too small in my opinion. have a look at the attched picture.

so long an keep corona away !

<img width="146" alt="todoist_03" src="https://user-images.githubusercontent.com/64371589/80438223-f2d25800-8903-11ea-9e52-801fa0fc4295.png">

**Comment by cbrooker** [comment]
Hi Perlchamp,

This can absolutely be done in the CSS.

In the MMM-Todoist.css file add:
`.MMM-Todoist header {
    font-size: 24px;
}`

Any style you put in there will affect the title of the module. Size, color, padding, etc.

**Comment by perlchamp** [comment]
thank you. 
`header { font-size: 24pt; ...} `
makes the same, but your code is nicer !

**Comment by cbrooker** [comment]
If you do:
`header { font-size: 24pt; ...} `
It has a possible side effect of changing the header of all the other modules not just this one.

**Comment by perlchamp** [comment]
ok, thanks a lot.

stay healthy
