### ISSUE TITLE
Any way to hide the project name.

### ISSUE THREAD

**Issue by Bernard-h** [cbrooker/MMM-Todoist#90]
Hi , first of all many thanks for the development and continuing support from creator and users. I dig this. At this time my use of this MMM-todosit module is solely to integrate the Alexa used shopping list (or to do list ) with the mirror. 

- The basics work well, the items get displayed from my inbox. However, all my future groceries will have "inbox" and a white ball displayed next to them. Is there any way to hide the <new inbox dot> and the <inbox name> ? On the one hand it could be done by coding parameters or perhaps to change the fontcolor of the tags to black... anyway. If someone could have a look.

I am grateful as always. 
![Schermafbeelding 2021-03-15 om 14 29 26](https://user-images.githubusercontent.com/60395872/111160922-ddf1c800-859a-11eb-8a74-1df1f175283c.png)

**Comment by cbrooker** [comment]
Hi Bernard-h

Yes! Set "showProject" to false in your config.

**Comment by Bernard-h** [comment]
Fantastic sir, Many thanks and closing.
